  
const menu = [
  {
    id: 1,
    title: 'house special',
    category: 'burgers',
    price: 12.15,
    img:require('./Images/burger1.jpg'),
    desc: `Bacon, cheese, pickles, tomato, lettuce, egg`,
  },
  {
    id: 2,
    title: 'house special',
    category: 'burgers',
    price: 12.15,
    img:require('./Images/burger1.jpg'),
    desc: `Bacon, cheese, pickles, tomato, lettuce, egg`,
  },
  {
    id: 3,
    title: 'house special',
    category: 'burgers',
    price: 12.15,
    img:require('./Images/burger1.jpg'),
    desc: `Bacon, cheese, pickles, tomato, lettuce, egg`,
  },
  {
    id: 4,
    title: 'house special',
    category: 'burgers',
    price: 12.15,
    img:require('./Images/burger1.jpg'),
    desc: `Bacon, cheese, pickles, tomato, lettuce, egg`,
  },
  {
    id: 5,
    title: 'house special',
    category: 'burgers',
    price: 12.15,
    img:require('./Images/burger1.jpg'),
    desc: `Bacon, cheese, pickles, tomato, lettuce, egg`,
  },
  {
    id: 6,
    title: 'house special',
    category: 'burgers',
    price: 12.15,
    img:require('./Images/burger1.jpg'),
    desc: `Bacon, cheese, pickles, tomato, lettuce, egg`,
  },
  {
    id: 7,
    title: 'coke',
    category: 'drinks',
    price: 2.15,
    img:require('./Images/drink1.jpg'),
    desc: `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.`,
  },
  {
    id: 8,
    title: 'coke',
    category: 'drinks',
    price: 2.15,
    img:require('./Images/drink1.jpg'),
    desc: `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.`,
  },
  {
    id: 9,
    title: 'coke',
    category: 'drinks',
    price: 2.15,
    img:require('./Images/drink1.jpg'),
    desc: `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.`,
  },
  {
    id: 10,
    title: 'chips',
    category: 'sides',
    price: 3.55,
    img:require('./Images/side1.jpg'),
    desc: `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.`,
  },
  {
    id: 11,
    title: 'chips',
    category: 'sides',
    price: 3.55,
    img:require('./Images/side1.jpg'),
    desc: `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.`,
  },
  {
    id: 12,
    title: 'chips',
    category: 'sides',
    price: 3.55,
    img:require('./Images/side1.jpg'),
    desc: `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.`,
  },
  {
    id: 13,
    title: 'chips',
    category: 'sides',
    price: 3.55,
    img:require('./Images/side1.jpg'),
    desc: `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.`,
  },
  {
    id: 14,
    title: 'brownie',
    category: 'desserts',
    price: 3.55,
    img:require('./Images/dessert1.jpg'),
    desc: `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.`,
  },
  {
    id: 15,
    title: 'brownie',
    category: 'desserts',
    price: 3.55,
    img:require('./Images/dessert1.jpg'),
    desc: `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.`,
  },
  {
    id: 16,
    title: 'brownie',
    category: 'desserts',
    price: 3.55,
    img:require('./Images/dessert1.jpg'),
    desc: `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.`,
  },
  {
    id: 17,
    title: 'brownie',
    category: 'desserts',
    price: 3.55,
    img:require('./Images/dessert1.jpg'),
    desc: `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.`,
  }
]
export default menu
